import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.0.0/firebase-app.js';
import {getAuth,GoogleAuthProvider,signInWithPopup,signInWithRedirect,getRedirectResult,onAuthStateChanged,signOut} from 'https://www.gstatic.com/firebasejs/12.0.0/firebase-auth.js';
import {getFirestore,collection,doc,setDoc,deleteDoc,onSnapshot,writeBatch} from 'https://www.gstatic.com/firebasejs/12.0.0/firebase-firestore.js';
const firebaseConfig={apiKey:'AIzaSyAnixK_4l4_ubEKwVZOabharyQAzjWSncM',authDomain:'sharon-7c160.firebaseapp.com',projectId:'sharon-7c160',storageBucket:'sharon-7c160.firebasestorage.app',messagingSenderId:'932603132482',appId:'1:932603132482:web:93261dcaa35c50c9074bdb'};
const firebaseApp=initializeApp(firebaseConfig),auth=getAuth(firebaseApp),firestore=getFirestore(firebaseApp),provider=new GoogleAuthProvider();
const $=s=>document.querySelector(s);const storeKey='sharon-calendar-v1';let events=JSON.parse(localStorage.getItem(storeKey)||'[]'),startupLocal=[...events],currentUser=null,stopEvents=null;let view=new Date();view.setDate(1);let selectedFiles=[];let selectedDay='';
const dbPromise=new Promise((ok,no)=>{const r=indexedDB.open('SharonCalendarFiles',1);r.onupgradeneeded=()=>r.result.createObjectStore('files',{keyPath:'id'});r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});
async function dbPut(x){const db=await dbPromise;return new Promise((ok,no)=>{const r=db.transaction('files','readwrite').objectStore('files').put(x);r.onsuccess=ok;r.onerror=()=>no(r.error)})}async function dbGet(id){const db=await dbPromise;return new Promise(ok=>{const r=db.transaction('files').objectStore('files').get(id);r.onsuccess=()=>ok(r.result)})}async function dbDelete(id){const db=await dbPromise;db.transaction('files','readwrite').objectStore('files').delete(id)}
const pad=n=>String(n).padStart(2,'0');const dateKey=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;const localValue=d=>`${dateKey(d)}T${pad(d.getHours())}:${pad(d.getMinutes())}`;const esc=s=>(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem(storeKey,JSON.stringify(events));render();fillFilters()}function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
const cloudEvent=ev=>Object.fromEntries(Object.entries(ev).filter(([k])=>k!=='files'));
async function syncEvent(ev){if(currentUser)await setDoc(doc(firestore,'users',currentUser.uid,'events',ev.id),cloudEvent(ev))}
async function removeCloudEvent(id){if(currentUser)await deleteDoc(doc(firestore,'users',currentUser.uid,'events',id))}
function listenForEvents(user){if(stopEvents)stopEvents();const ref=collection(firestore,'users',user.uid,'events');stopEvents=onSnapshot(ref,async snap=>{const marker='sharon-migrated-'+user.uid;if(snap.empty&&startupLocal.length&&!localStorage.getItem(marker)){localStorage.setItem(marker,'1');const batch=writeBatch(firestore);startupLocal.forEach(ev=>batch.set(doc(ref,ev.id),cloudEvent(ev)));try{await batch.commit();toast('原有行程已同步至 Firebase')}catch(err){localStorage.removeItem(marker);toast('同步失敗，請檢查資料庫規則')}return}const localFiles=new Map(events.map(ev=>[ev.id,ev.files||[]]));events=snap.docs.map(d=>({...d.data(),id:d.id,files:localFiles.get(d.id)||[]}));save();$('#loginStatus').textContent='已連線 Firebase'},err=>{$('#loginStatus').textContent='Firebase 連線失敗';toast(err.code==='permission-denied'?'請先設定 Firestore 安全規則':'Firebase 連線失敗')})}
function occurrences(ev,from,to){let d=new Date(ev.start),out=[],limit=0;while(d<=to&&limit++<500){if(d>=from)out.push(new Date(d));if(ev.repeat==='none'||!ev.repeat)break;if(ev.repeat==='daily')d.setDate(d.getDate()+1);else if(ev.repeat==='weekly')d.setDate(d.getDate()+7);else if(ev.repeat==='monthly')d.setMonth(d.getMonth()+1);else d.setDate(d.getDate()+(+ev.interval||1))}return out}
function eventsForDay(key){const day=new Date(key+'T00:00'),end=new Date(key+'T23:59:59');return events.flatMap(ev=>occurrences(ev,day,end).map(at=>({ev,at}))).filter(x=>{const q=$('#searchInput').value.trim().toLowerCase(),f=$('#filterSelect').value;return(!q||[x.ev.title,x.ev.content,x.ev.tag,x.ev.category].join(' ').toLowerCase().includes(q))&&(!f||x.ev.tag===f)}).sort((a,b)=>a.at-b.at)}
function render(){const y=view.getFullYear(),m=view.getMonth();$('#monthTitle').textContent=`${y}年${m+1}月`;const first=new Date(y,m,1),start=new Date(y,m,1-first.getDay()),today=dateKey(new Date());let html='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=dateKey(d),items=eventsForDay(key),other=d.getMonth()!==m;html+=`<article class="day ${other?'other':''} ${key===today?'today':''}" data-day="${key}"><div class="day-number"><span>${d.getDate()}</span><button title="新增">＋</button></div>${items.slice(0,2).map(({ev,at})=>`<button class="event-pill" data-id="${ev.id}" style="--event-color:${ev.color}" title="${esc(ev.title)}">${pad(at.getHours())}:${pad(at.getMinutes())} ${esc(ev.title)}</button>`).join('')}${items.length>2?`<button class="more">還有 ${items.length-2} 筆</button>`:''}</article>`}$('#calendar').innerHTML=html}
function fillFilters(){const current=$('#filterSelect').value,tags=[...new Set(events.map(e=>e.tag).filter(Boolean))];$('#filterSelect').innerHTML='<option value="">全部標籤</option>'+tags.map(t=>`<option ${t===current?'selected':''}>${esc(t)}</option>`).join('')}
function openNew(key=dateKey(new Date())){$('#eventForm').reset();$('#eventId').value='';$('#color').value='#3b82f6';$('#modalKicker').textContent='新增';$('#modalTitle').textContent='新增排程';$('#deleteBtn').hidden=true;$('#savedFiles').innerHTML='';selectedFiles=[];renderPending();const d=new Date(key+'T09:00');$('#start').value=localValue(d);$('#eventDialog').showModal()}
async function openEdit(id){const ev=events.find(x=>x.id===id);if(!ev)return;$('#eventId').value=ev.id;for(const k of ['color','tag','category','title','content','start','end','repeat','interval'])$('#'+k).value=ev[k]||({repeat:'none',interval:1}[k]??'');$('#intervalWrap').hidden=ev.repeat!=='custom';$('#modalKicker').textContent='編輯';$('#modalTitle').textContent='編輯排程';$('#deleteBtn').hidden=false;selectedFiles=[];renderPending();await renderSaved(ev);$('#dayDialog').close();$('#eventDialog').showModal()}
function renderPending(){$('#pendingFiles').innerHTML=selectedFiles.map((f,i)=>`<div class="file-item"><span>📎</span><div class="file-meta"><strong>${esc(f.name)}</strong><small>${formatSize(f.size)}</small></div><div class="file-actions"><button type="button" data-remove-pending="${i}">移除</button></div></div>`).join('')}
async function renderSaved(ev){let html='';for(const f of ev.files||[]){const rec=await dbGet(f.id);let url=rec?URL.createObjectURL(rec.blob):'';html+=`<div class="file-item">${rec&&f.type.startsWith('image/')?`<img class="file-thumb" src="${url}">`:'<span>📄</span>'}<div class="file-meta"><strong>${esc(f.name)}</strong><small>${formatSize(f.size)}</small></div><div class="file-actions">${rec?(f.type.startsWith('image/')?`<button type="button" data-preview="${f.id}">查看</button>`:`<a href="${url}" download="${esc(f.name)}">下載</a>`):''}<button type="button" data-remove-saved="${f.id}">移除</button></div></div>`}$('#savedFiles').innerHTML=html}
const formatSize=n=>n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB';
function openDay(key){selectedDay=key;const list=eventsForDay(key);$('#dayTitle').textContent=key.replaceAll('-',' / ');$('#dayEvents').innerHTML=list.length?list.map(({ev,at})=>`<article class="day-card" data-id="${ev.id}" style="--event-color:${ev.color}"><h3>${esc(ev.title)}</h3><p>${pad(at.getHours())}:${pad(at.getMinutes())}　${esc(ev.tag||ev.category)}</p>${ev.content?`<p>${esc(ev.content)}</p>`:''}${ev.files?.length?`<p>📎 ${ev.files.length} 個附件</p>`:''}</article>`).join(''):'<p style="color:#64748b">這天還沒有排程</p>';$('#dayDialog').showModal()}
$('#eventForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('#eventId').value||crypto.randomUUID(),old=events.find(x=>x.id===id),files=old?.files?[...old.files]:[];for(const f of selectedFiles){const fid=crypto.randomUUID();await dbPut({id:fid,blob:f});files.push({id:fid,name:f.name,size:f.size,type:f.type||'application/octet-stream'})}const ev={id,files,...Object.fromEntries(['color','tag','category','title','content','start','end','repeat','interval'].map(k=>[k,$('#'+k).value]))};if(ev.end&&new Date(ev.end)<new Date(ev.start)){toast('結束時間不能早於開始時間');return}events=old?events.map(x=>x.id===id?ev:x):[...events,ev];save();try{await syncEvent(ev);$('#eventDialog').close();toast(old?'排程已更新並同步':'排程已新增並同步')}catch(err){toast('無法同步，請檢查 Firebase 設定')}});
$('#fileInput').addEventListener('change',e=>{const list=[...e.target.files];if(list.some(f=>f.size>10*1024*1024)){toast('單一檔案不能超過 10MB');return}selectedFiles.push(...list);renderPending();e.target.value=''});$('#pendingFiles').onclick=e=>{const b=e.target.closest('[data-remove-pending]');if(b){selectedFiles.splice(+b.dataset.removePending,1);renderPending()}};$('#savedFiles').onclick=async e=>{const preview=e.target.closest('[data-preview]');if(preview){const rec=await dbGet(preview.dataset.preview),ev=events.find(x=>x.id===$('#eventId').value),meta=ev?.files.find(x=>x.id===preview.dataset.preview);if(rec){$('#previewImage').src=URL.createObjectURL(rec.blob);$('#previewName').textContent=meta?.name||'圖片';$('#imageDialog').showModal()}return}const b=e.target.closest('[data-remove-saved]');if(!b)return;const ev=events.find(x=>x.id===$('#eventId').value);await dbDelete(b.dataset.removeSaved);ev.files=ev.files.filter(x=>x.id!==b.dataset.removeSaved);save();renderSaved(ev)};
$('#deleteBtn').onclick=async()=>{if(!confirm('確定刪除這筆排程？'))return;const id=$('#eventId').value,ev=events.find(x=>x.id===id);try{await removeCloudEvent(id);for(const f of ev?.files||[])await dbDelete(f.id);events=events.filter(x=>x.id!==id);save();$('#eventDialog').close();toast('排程已刪除')}catch(err){toast('刪除失敗，請檢查 Firebase 設定')}};
$('#calendar').onclick=e=>{const pill=e.target.closest('.event-pill');if(pill)return openEdit(pill.dataset.id);const day=e.target.closest('.day');if(!day)return;if(e.target.closest('.day-number button'))openNew(day.dataset.day);else openDay(day.dataset.day)};$('#dayEvents').onclick=e=>{const c=e.target.closest('[data-id]');if(c)openEdit(c.dataset.id)};
$('#addBtn').onclick=()=>openNew();$('#addForDay').onclick=()=>{$('#dayDialog').close();openNew(selectedDay)};$('#prevBtn').onclick=()=>{view.setMonth(view.getMonth()-1);render()};$('#nextBtn').onclick=()=>{view.setMonth(view.getMonth()+1);render()};$('#todayBtn').onclick=()=>{view=new Date();view.setDate(1);render()};$('#searchInput').oninput=render;$('#filterSelect').onchange=render;$('#repeat').onchange=e=>$('#intervalWrap').hidden=e.target.value!=='custom';document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#eventDialog').close());$('[data-day-close]').onclick=()=>$('#dayDialog').close();$('#imageClose').onclick=()=>$('#imageDialog').close();$('#imageDialog').onclick=e=>{if(e.target===$('#imageDialog'))$('#imageDialog').close()};
$('#loginBtn').onclick=async()=>{try{$('#loginStatus').textContent='正在開啟 Google 登入⋯';await signInWithPopup(auth,provider)}catch(err){if(['auth/popup-blocked','auth/cancelled-popup-request','auth/operation-not-supported-in-this-environment'].includes(err.code))await signInWithRedirect(auth,provider);else $('#loginStatus').textContent=err.code==='auth/unauthorized-domain'?'請先將 GitHub Pages 加入授權網域':'登入未完成，請再試一次'}};
$('#logoutBtn').onclick=()=>signOut(auth);
getRedirectResult(auth).catch(()=>{});
onAuthStateChanged(auth,user=>{currentUser=user;if(user){$('#loginGate').hidden=true;$('#authUser').hidden=false;$('#logoutBtn').hidden=false;$('#authUser').textContent=user.displayName||user.email;listenForEvents(user)}else{if(stopEvents){stopEvents();stopEvents=null}$('#loginGate').hidden=false;$('#authUser').hidden=true;$('#logoutBtn').hidden=true;$('#loginStatus').textContent='請登入後開始使用';}});
fillFilters();render();
